name: elements-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: elements-${{ github.ref_name }}-mingw.zip
    steps:
      - name: git clone SFML
        run: git clone --branch master https://github.com/cycfi/elements.git

      - name: cmake SFML
        shell: cmd
        run: cd elements && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="build/elements" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd elements\build && mingw32-make install
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: "elements/build"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
